#!/usr/local/bin/php-cgi -f
<?php
require_once("config.inc");
require_once("services.inc");
require_once("captiveportal.inc");

global $cpzone;
global $cpzoneid;

$cpzone = "iwip";
$newcp =& $config['captiveportal'][$cpzone];
$cpzoneid = $newcp['zoneid'];

unset($newcp['enable']);

write_config();

captiveportal_configure_zone($newcp);

unset($newcp);
filter_configure();

?>
